# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c67aac4278e220ea2c20a6dd9ea19552d1d8cd7114faf6daf7f61f931583dcf36e2dd69ac57149451d3289fde2cb31f0a0e9acf52027e7761a4c997c3f98b7f9

test:
  secret_key_base: 3744b3c3ea64ad72a2a8c556617a558a224c0e84b50fb03e5115a00d0ae1d8ee93ee64383b0c13fd92218be708109938a06db511ba0300649affe3433b17a7e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
